name: kaya_tester
description: Tester of source modules for the Kagayaku app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  kagayaku_modules:
    git:
      url: https://github.com/Zerolmntrix/kagayaku-modules.git
      ref: dev

  #ui
  phosphor_flutter: ^2.0.0
  dotted_border: ^2.0.0
  another_flushbar: ^1.12.30

  #core
  archive: ^3.3.7
  flutter_dropzone: ^3.0.6

dev_dependencies:
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
